### ISSUE TITLE
How is your solution different from other existing ones?

### ISSUE THREAD

**Issue by 4n70w4** [pdmfc/nova-action-button#2]
Hello! I know at least 3 ways to invoke an action on a resource from an index table. Why one more of your fourth? I'm not nitpicking, just Occam's razor.

Why not an default Nova `->showOnTableRow()`?

![image](https://user-images.githubusercontent.com/38257723/79045237-b4a21c80-7c12-11ea-9063-a5842f0987de.png)

https://nova.laravel.com/docs/3.0/actions/defining-actions.html

Or https://novapackages.com/packages/dillingham/nova-button package?

**Comment by skoyah** [comment]
Hi @4n70w4 and thanks for the feedback!

I'm aware of the other options available in the community and also how this one is a bit different.

- The default Nova `->showOnTableRow()` creates a predefined list of whatever actions you declare in your resource while with this package you can run actions dynamically for each single table row.
For example you can define the action class by checking some condition. another difference is that  you cannot place the default inline action anywhere but the end of the table row.

- About the dillingham/nova-button package, as you can see on [this thread](https://github.com/dillingham/nova-button/issues/27) you are not able to directly run actions like Nova does.

That being said, both options that your referenced are very good and they serve a specific purpose. As this one does.
