### ISSUE TITLE
Use field on detail view

### ISSUE THREAD

**Issue by jerrychee94** [pdmfc/nova-action-button#4]
Hi,

Would appreciate if we can have support for detail view. I tried creating custom field to allow action on detail view. It works well but it will not refresh the page.

It emits 'actionExecuted' to parent vue but nothing happens. The workaround that I have is to use 

```
                window.setTimeout(() => {
                    this.$router.go()
                }, 200)
```
but it's too hacky :(

**Comment by skoyah** [comment]
Hey @jerrychee94 . I think this can be done. Added to the milestone and will be tackling this feature on the next days.

**Comment by jerrychee94** [comment]
I would love to contribute but currently my way of doing (see 1st comment) is not the right way :(. I have no idea how to emit actionExecuted event to detail.vue. But works for Index.vue

**Comment by 949mac** [comment]
+1 for this

**Comment by skoyah** [comment]
@jerrychee94 , @949mac, I've added the ability to use the field on the detail view with the new release (v0.3) 0bfa986bdac16e45e8ab16878970a436e8560580

Thanks once again for the idea and would be nice to know your feedback! 😉

**Comment by jerrychee94** [comment]
Thank you @skoyah  !!
