### ISSUE TITLE
Accept an Action class path OR instance

### ISSUE THREAD

**Issue by joshgaber** [pdmfc/nova-action-button#7]
It would be helpful if the `action()` function was able to accept an instance of an action, in cases where the constructor of that action may have been overloaded, or where additional method calls need to be made on the action. For example:

```php
public function fields()
{
    return [
        ActionButton::make('Action')
            ->action(new ChangeRole('super_admin'), $this->id)
    ];
}
```

```php
public function fields()
{
    return [
        ActionButton::make('Action')
            ->action(new ChangeRole()->omitRole('super_admin'), $this->id)
    ];
}
```

**Comment by skoyah** [comment]
Hi @joshgaber. 

Feel free to contribute with a PR.

Meanwhile I'll add it as a milestone and will tackle this feature request as soon as I can.

Thanks! :)

**Comment by joshgaber** [comment]
Thanks @skoyah. I have a fix ready, but unfortunately, I do not have permission to push my branch to GitHub.

**Comment by skoyah** [comment]
Did you fork the repo? I think you can just submit a PR from your forked repo against the original repo
