### ISSUE TITLE
Vue throws warnings when displayed on Detail view 

### ISSUE THREAD

**Issue by joshgaber** [pdmfc/nova-action-button#8]
When action buttons are displayed on resource detail pages, the following warning are thrown by Vue:

* `[Vue warn]: Invalid prop: type check failed for prop "resource". Expected String with value "[object Object]", got Object`

* `[Vue warn]: Invalid prop: type check failed for prop "resourceId". Expected Number with value 1, got String with value "1"`

**Comment by skoyah** [comment]
@joshgaber I was not able to replicate your issue. Could you show me a sample code?

**Comment by skoyah** [comment]
Closing this issue since I couldn't replicate it and got no feedback for quite some time.
